library(ggplot2)
library(dplyr)
library(MASS)

housedf = read.csv('./data/Ames_HousePrice_processed.csv')

plotbase = housedf %>% ggplot(aes(y=SalePrice))
plotlogbase = housedf %>% ggplot(aes(y=log(SalePrice)))

plotbase + geom_boxplot(aes(x = MSZoning))
plotbase + geom_boxplot(aes(x=Street))
plotbase + geom_boxplot(aes(x=Alley))
plotbase + geom_boxplot(aes(x=LotShape))
plotbase + geom_boxplot(aes(x=LandContour))
plotbase + geom_boxplot(aes(x=Utilities))
plotbase + geom_boxplot(aes(x=LotConfig))
plotbase + geom_boxplot(aes(x=LandSlope))
plotbase + geom_boxplot(aes(x=Neighborhood))
plotbase + geom_boxplot(aes(x=Condition1))
plotbase + geom_boxplot(aes(x=Condition2))
plotbase + geom_boxplot(aes(x=BldgType))
plotbase + geom_boxplot(aes(x=HouseStyle))
plotbase + geom_boxplot(aes(x=RoofStyle))
plotbase + geom_boxplot(aes(x=RoofMatl))
plotbase + geom_boxplot(aes(x=Exterior1st))
plotbase + geom_boxplot(aes(x=Exterior2nd))
plotbase + geom_boxplot(aes(x=MasVnrType))
plotbase + geom_boxplot(aes(x=ExterQual))
plotbase + geom_boxplot(aes(x=ExterCond))
plotbase + geom_boxplot(aes(x=Foundation))
plotbase + geom_boxplot(aes(x=BsmtQual))
plotbase + geom_boxplot(aes(x=BsmtCond))
plotbase + geom_boxplot(aes(x=BsmtExposure))
plotbase + geom_boxplot(aes(x=BsmtFinType1))
plotbase + geom_boxplot(aes(x=Heating))
plotbase + geom_boxplot(aes(x=HeatingQC))
plotbase + geom_boxplot(aes(x=CentralAir))
plotbase + geom_boxplot(aes(x=Electrical))
plotbase + geom_boxplot(aes(x=KitchenQual))
plotbase + geom_boxplot(aes(x=FireplaceQu))
plotbase + geom_boxplot(aes(x=GarageType))
plotbase + geom_boxplot(aes(x=GarageFinish))
plotbase + geom_boxplot(aes(x=GarageQual))
plotbase + geom_boxplot(aes(x=GarageCond))
plotbase + geom_boxplot(aes(x=PoolQC))
plotbase + geom_boxplot(aes(x=Fence))


plotbase + geom_point(aes(x=GrLivArea))
plotlogbase + geom_point(aes(x=log(GrLivArea)))
plotbase + geom_point(aes(x=LotArea))
plotlogbase + geom_point(aes(x=log(LotArea)))
plotbase + geom_point(aes(x=LotFrontage))
plotlogbase + geom_point(aes(x=log(LotFrontage)))
plotbase + geom_point(aes(x=OverallQual))
plotbase + geom_point(aes(x=OverallCond))
plotbase + geom_point(aes(x=MasVnrArea))
plotbase + geom_point(aes(x=BsmtFinSF1))
plotbase + geom_point(aes(x=BsmtFinSF2))
plotbase + geom_point(aes(x=BsmtUnfSF))
plotbase + geom_point(aes(x=TotalBsmtSF))
plotbase + geom_point(aes(x=X1stFlrSF))
plotbase + geom_point(aes(x=X2ndFlrSF))
plotbase + geom_point(aes(x=LowQualFinSF))
plotbase + geom_point(aes(x=BsmtFullBath))
plotbase + geom_point(aes(x=BsmtHalfBath))
plotbase + geom_point(aes(x=FullBath))
plotbase + geom_point(aes(x=HalfBath))
plotbase + geom_point(aes(x=BedroomAbvGr))
plotbase + geom_point(aes(x=KitchenAbvGr))
plotbase + geom_point(aes(x=TotRmsAbvGrd))
plotbase + geom_point(aes(x=Fireplaces))
plotbase + geom_point(aes(x=GarageCars))
plotbase + geom_point(aes(x=GarageArea))
plotbase + geom_point(aes(x=WoodDeckSF))
plotbase + geom_point(aes(x=OpenPorchSF))
plotbase + geom_point(aes(x=EnclosedPorch))
plotbase + geom_point(aes(x=X3SsnPorch))
plotbase + geom_point(aes(x=ScreenPorch))
plotbase + geom_point(aes(x=PoolArea))
plotbase + geom_point(aes(x=YrSold))
plotbase + geom_point(aes(x=ExteriorSF))
plotbase + geom_point(aes(x=AgeAtSale))

ols = lm(SalePrice ~ . - X - PID - Prop_Addr - MA_Ownr1 - MA_Ownr2 - Latitude - Longitude, housedf)

summary(ols)
plot(ols)

bc = boxcox(ols)
lambda = bc$x[which.max(bc$y)]

bc_ols = lm(((SalePrice^lambda-1)/lambda) ~ . - X - PID - Prop_Addr - MA_Ownr1 - MA_Ownr2 - Latitude - Longitude, housedf)
summary(bc_ols)
plot(bc_ols)

